name: Daily Rebuild

on:
  schedule:
    - cron:  '0 12 * * *'
  workflow_dispatch:  # This line adds a manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Rebuild
      run: |
        curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_YourProjectId/YourVercelDeployHook
