name: Daily Rebuild

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Rebuild
      run: |
        curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_lMxfZAiCW7mQtSg1vSh0GFVvQcZF/2z6ZpZWwkQ
